# **Bussiness Question**
1. Apa saja faktor yang mempengaruhi nilai dari skor_stress dan apa pemicu utamanya?

In [1]:
import pandas as pd

# **Data Gathering**

In [2]:
df = pd.read_csv("../data/raw/university_student_stress_dataset.csv")
df.head()

,Age,Gender,Study_Hours,Class_Attendance,Tuition,Exam_Frequency,Assignment_Load,Sleep_Hours,Caffeine_Intake_mg,Physical_Exercise,Social_Media_Use,Screen_Time,Family_Income_Level,Peer_Pressure,Family_Support,Anxiety_Level,University_Type,Stress_Score,Stress_Level
0,24,Male,9.0,71.0,No,7,4.0,6.0,200,Yes,6.0,9.0,Low,6.0,3.0,5.0,National University,20,Medium
1,24,Female,8.0,43.0,Yes,6,8.0,5.0,0,Yes,6.0,8.0,Medium,3.0,7.0,8.0,National University,22,High
2,21,Female,4.0,56.0,Yes,3,6.0,5.0,100,Yes,7.0,9.0,Low,2.0,5.0,3.0,Private University,16,Medium
3,23,Female,4.0,46.0,No,8,6.0,8.0,50,No,5.0,6.0,Medium,8.0,6.0,5.0,Private University,16,Medium
4,20,Male,8.0,46.0,No,5,1.0,6.0,200,Yes,0.0,7.0,Medium,5.0,6.0,2.0,National University,1,Low

# **Data Assesing**

In [3]:
# Cek Kolom dan Tipe data
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3060 entries, 0 to 3059
Data columns (total 19 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Age                  3060 non-null   int64
 1   Gender               3060 non-null   str
 2   Study_Hours          3042 non-null   float64
 3   Class_Attendance     3043 non-null   float64
 4   Tuition              3060 non-null   str
 5   Exam_Frequency       3060 non-null   int64
 6   Assignment_Load      3045 non-null   float64
 7   Sleep_Hours          3046 non-null   float64
 8   Caffeine_Intake_mg   3035 non-null   str
 9   Physical_Exercise    3051 non-null   str
 10  Social_Media_Use     3049 non-null   float64
 11  Screen_Time          3043 non-null   float64
 12  Family_Income_Level  3045 non-null   str
 13  Peer_Pressure        3041 non-null   float64
 14  Family_Support       3039 non-null   float64
 15  Anxiety_Level        3051 non-null   float64
 16  University_Type      3060 non-null   str
 17  Stress_Score         3060 non-null   int64
 18  Stress_Level         3060 non-null   str
dtypes: float64(9), int64(3), str(7)
memory usage: 454.3 KB

In [4]:
# Mengecek jumlah dan persentase missing value
missing_summary = pd.DataFrame({
    'missing_count': df.isna().sum(),
    'missing_percentage': df.isna().mean() * 100
}).sort_values(by='missing_percentage', ascending=False)

missing_summary

                     missing_count  missing_percentage
Caffeine_Intake_mg              25            0.816993
Family_Support                  21            0.686275
Peer_Pressure                   19            0.620915
Study_Hours                     18            0.588235
Class_Attendance                17            0.555556
Screen_Time                     17            0.555556
Family_Income_Level             15            0.490196
Assignment_Load                 15            0.490196
Sleep_Hours                     14            0.457516
Social_Media_Use                11            0.359477
Anxiety_Level                    9            0.294118
Physical_Exercise                9            0.294118
Age                              0            0.000000
Gender                           0            0.000000
Exam_Frequency                   0            0.000000
Tuition                          0            0.000000
University_Type                  0            0.000000
Stress_Score                     0            0.000000
Stress_Level                     0            0.000000

In [5]:
# Cek Duplikat Data
print("Jumlah Data duplikat:", df.duplicated().sum())

Jumlah Data duplikat: 60

In [6]:
# Cek Outlier dan Keakuratan Data
df.describe(include="all")

,Age,Gender,Study_Hours,Class_Attendance,Tuition,Exam_Frequency,Assignment_Load,Sleep_Hours,Caffeine_Intake_mg,Physical_Exercise,Social_Media_Use,Screen_Time,Family_Income_Level,Peer_Pressure,Family_Support,Anxiety_Level,University_Type,Stress_Score,Stress_Level
count,3060.000000,3060,3042.000000,3043.000000,3060,3060.000000,3045.000000,3046.000000,3035,3051,3049.000000,3043.000000,3045,3041.000000,3039.000000,3051.000000,3060,3060.000000,3060
unique,NaN,8,NaN,NaN,8,NaN,NaN,NaN,23,8,NaN,NaN,11,NaN,NaN,NaN,12,NaN,9
top,NaN,Female,NaN,NaN,No,NaN,NaN,NaN,100,No,NaN,NaN,Medium,NaN,NaN,NaN,Private University,NaN,Medium
freq,NaN,1551,NaN,NaN,1556,NaN,NaN,NaN,574,1556,NaN,NaN,1336,NaN,NaN,NaN,1011,NaN,1434
mean,21.529412,NaN,4.492110,68.910286,NaN,5.034967,4.990805,6.524294,NaN,NaN,3.498524,5.917516,NaN,4.983229,5.037512,4.999344,NaN,11.868954,NaN
std,1.736702,NaN,2.893956,17.519863,NaN,2.625177,2.603933,1.709982,NaN,NaN,2.332319,3.186216,NaN,2.577748,2.575887,2.569557,NaN,6.788796,NaN
min,17.000000,NaN,-1.000000,-5.000000,NaN,0.000000,-2.000000,0.000000,NaN,NaN,0.000000,1.000000,NaN,1.000000,0.000000,1.000000,NaN,-9.000000,NaN
25%,20.000000,NaN,2.000000,54.000000,NaN,3.000000,3.000000,5.000000,NaN,NaN,2.000000,3.000000,NaN,3.000000,3.000000,3.000000,NaN,7.000000,NaN
50%,22.000000,NaN,4.000000,69.000000,NaN,5.000000,5.000000,7.000000,NaN,NaN,3.000000,6.000000,NaN,5.000000,5.000000,5.000000,NaN,12.000000,NaN
75%,23.000000,NaN,7.000000,84.000000,NaN,7.000000,7.000000,8.000000,NaN,NaN,5.000000,9.000000,NaN,7.000000,7.000000,7.000000,NaN,17.000000,NaN
max,31.000000,NaN,18.000000,105.000000,NaN,15.000000,12.000000,14.000000,NaN,NaN,15.000000,11.000000,NaN,11.000000,9.000000,9.000000,NaN,33.000000,NaN

In [7]:
categorical_columns = df.select_dtypes(include=["object", "category", "string"]).columns

for i, feature in enumerate(categorical_columns, start=1):
    unique_values = df[feature].dropna().unique()
    
    print(f"{i}. {feature}")
    print(f"   Jumlah unique values: {df[feature].nunique(dropna=True)}")
    print(f"   Sample unique values: {unique_values[:10]}")
    print("-" * 50)

1. Gender
   Jumlah unique values: 8
   Sample unique values: <StringArray>
['Male', 'Female', ' male', 'Female ', ' female', 'FEMALE', 'MALE', 'Male ']
Length: 8, dtype: str
--------------------------------------------------
2. Tuition
   Jumlah unique values: 8
   Sample unique values: <StringArray>
['No', 'Yes', 'NO', 'yes', ' No ', 'YES', 'no', ' Yes ']
Length: 8, dtype: str
--------------------------------------------------
3. Caffeine_Intake_mg
   Jumlah unique values: 23
   Sample unique values: <StringArray>
['200', '0', '100', '50', '150', '300', '250', '250 mg', '450', '100 mg']
Length: 10, dtype: str
--------------------------------------------------
4. Physical_Exercise
   Jumlah unique values: 8
   Sample unique values: <StringArray>
['Yes', 'No', ' NO', ' YES', 'Yes ', 'no', 'No ', 'yes']
Length: 8, dtype: str
--------------------------------------------------
5. Family_Income_Level
   Jumlah unique values: 11
   Sample unique values: <StringArray>
[     'Low',   'Medium',     'High',      'LOW',   'MEDIUM',     ' low',
 ' Medium ',   'medium',     'HIGH',     'Low ']
Length: 10, dtype: str
--------------------------------------------------
6. University_Type
   Jumlah unique values: 12
   Sample unique values: <StringArray>
[  'National University',    'Private University',     'Public University',
     'PUBLIC UNIVERSITY',    'private university',   ' Public University ',
 ' National University ',   'NATIONAL UNIVERSITY',    'PRIVATE UNIVERSITY',
  ' Private University ']
Length: 10, dtype: str
--------------------------------------------------
7. Stress_Level
   Jumlah unique values: 9
   Sample unique values: <StringArray>
['Medium', 'High', 'Low', 'medium', 'low', ' Medium ', 'high', ' Low ',
 ' High ']
Length: 9, dtype: str
--------------------------------------------------

## **Data Understanding**
Penjelasan Setiap Data pada dataset.
1. **Age**: Usia Mahasiswa
2. **Exam_Frequency**: Seberapa sering ujian atau tes dilakukan
3. **Stress_Score**: Nilai Ukuran Seberapa Rendah atau Tinggi Stress
4. **Gender**: Jenis Kelamin
5. **Study_Hours**: Total Jam Belajar dalam satu Hari
6. **Class_Attendence**: Persentase Kehadiran per semester
7. **Assignment_Load**: Nilai Ukuran Seberapa Beban Tugas yang diberikan
8. **Sleep_Hours**: Total Jam Tidur per hari
9. **Social_Media_Use**: Total Jam Penggunaan Sosial Media dalam satu hari
10. **Screen_time**: Total Jam penggunaan Gadget dalam satu hari
11. **Physical_Exercise**: Status Mahasiswa Sering Olaharaga (Ya/Tidak)
12. **Family_Income_Level**: Tingkat Kekayaan Keluarga
13. **Peer_Presure**: Nilai Ukuran Seberapa tekanan yang dirasakan dari teman sebayanya
14. **Family_Support**: Nilai Ukuran Seberapa Mendukung Keluarga
15. **Anxiety_Level**: Nilai Ukuran Tingkat Kecemasan
16. **Stress_Score**: Nilai Ukuran Seberapa Stress Mahasiswa
17. **Stress_level**: Status Stress Berdasarkan Skornya

## **Insight**
1. Total Jumlah Missing values sebanyak **190 Baris**
2. Total Jumlah Duplikat Data sebanyak **60 Baris**
3. Terdapat kesalahan tipe data pada kolom **Caffeine_Intake_mg**
4. Terdapat Bilangan Negatif pada Kolom **Study_Hours,Class_Attendance,Assignment_Load,Stress_Score**
5. Terdapat Inconsistent Data pada kolom **Gender,Tuition,Caffeine_Intake_mg,Physical_Exercise,Family_Income_Level,University_Type,Stress_Level**
6. Terdapat Invalid Data pada kolom **Age,Class_Attandance,Exam_Frequency,Assignment_Load,Peer_Pressure**

# **Data Cleaning**

### Memperbaiki Invallid Data type

In [8]:
# Memperbaiki Tipe data Salah denga dikonversi menjadi numerik
df['Caffeine_Intake_mg'] = pd.to_numeric(df['Caffeine_Intake_mg'], errors='coerce')

In [9]:
"""
Memperbaiki Invalid pada kolom Study_Hours,Class_Attendance,Assignment_Load,Caffeine_Intake_mg,Stress_Score
Karena Memiliki nilai negatif yang seharusnya positif
"""
column = ["Study_Hours","Class_Attendance","Assignment_Load","Caffeine_Intake_mg","Stress_Score"]
for feature in column:
  df[feature] = df[feature].abs()

In [10]:
# Nilai Age = 31 berada di luar rentang valid dataset (18–24), sehingga dianggap sebagai kemungkinan typo dan dikoreksi menjadi 21.
df['Age'] = df['Age'].replace(31, 21)
# Satuan Persentase hanya memiliki Rentang (1-100)
df["Class_Attendance"] = df["Class_Attendance"].replace(105, df["Class_Attendance"].median())

# Nilainya diluar Rentang valid dataset (1-10)
df["Exam_Frequency"] = df["Exam_Frequency"].replace(15, df["Exam_Frequency"].median())
df["Assignment_Load"] = df["Assignment_Load"].replace(12, df["Assignment_Load"].median())
df["Peer_Pressure"] = df["Peer_Pressure"].replace(11, df["Peer_Pressure"].median())

### Memperbaiki Data Tidak Konsisten

In [11]:
# Memperbaiki data tidak konsisten pada kolom kategorikal
categorical_columns = df.select_dtypes(include=["object", "string", "category"]).columns

for feature in categorical_columns:
    df[feature] = (
        df[feature]
        .astype("string")
        .str.strip()
        .str.title()
    )

### Membersihkan Missing Value

In [12]:
# Membersihkan missing value pada data numerik
numeric_column = df.select_dtypes(include=["int64", "float64"]).columns
df[numeric_column] = df[numeric_column].fillna(df[numeric_column].median())

In [13]:
# Membersihkan missing value pada Data Kategorial
for feature in categorical_columns:
  df[feature] = df[feature].fillna(df[feature].mode()[0])

In [14]:
# Hapus Duplikat Data
df.drop_duplicates(inplace=True)

# **Data Validating**
Melakukan Validasi ulang pada data yang sudah dibersihkan

In [15]:
# Cek Kembali Missing Value
missing_values = df.isna().sum()
missing_values[missing_values > 0]

Series([], dtype: int64)

In [16]:
# Cek Kembali Duplikat Data
print("Jumlah Data duplikat:", df.duplicated().sum())

Jumlah Data duplikat: 0

In [17]:
# Cek Kembali Tipe Data
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 19 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Age                  3000 non-null   int64
 1   Gender               3000 non-null   string
 2   Study_Hours          3000 non-null   float64
 3   Class_Attendance     3000 non-null   float64
 4   Tuition              3000 non-null   string
 5   Exam_Frequency       3000 non-null   int64
 6   Assignment_Load      3000 non-null   float64
 7   Sleep_Hours          3000 non-null   float64
 8   Caffeine_Intake_mg   3000 non-null   float64
 9   Physical_Exercise    3000 non-null   string
 10  Social_Media_Use     3000 non-null   float64
 11  Screen_Time          3000 non-null   float64
 12  Family_Income_Level  3000 non-null   string
 13  Peer_Pressure        3000 non-null   float64
 14  Family_Support       3000 non-null   float64
 15  Anxiety_Level        3000 non-null   float64
 16  University_Type      3000 non-null   string
 17  Stress_Score         3000 non-null   int64
 18  Stress_Level         3000 non-null   string
dtypes: float64(10), int64(3), string(6)
memory usage: 445.4 KB

In [18]:
categorical_columns = df.select_dtypes(include=["object", "category", "string"]).columns

for i, feature in enumerate(categorical_columns, start=1):
    unique_values = df[feature].dropna().unique()
    
    print(f"{i}. {feature}")
    print(f"   Jumlah unique values: {df[feature].nunique(dropna=True)}")
    print(f"   Sample unique values: {unique_values[:10]}")
    print("-" * 50)

1. Gender
   Jumlah unique values: 2
   Sample unique values: <StringArray>
['Male', 'Female']
Length: 2, dtype: string
--------------------------------------------------
2. Tuition
   Jumlah unique values: 2
   Sample unique values: <StringArray>
['No', 'Yes']
Length: 2, dtype: string
--------------------------------------------------
3. Physical_Exercise
   Jumlah unique values: 2
   Sample unique values: <StringArray>
['Yes', 'No']
Length: 2, dtype: string
--------------------------------------------------
4. Family_Income_Level
   Jumlah unique values: 3
   Sample unique values: <StringArray>
['Low', 'Medium', 'High']
Length: 3, dtype: string
--------------------------------------------------
5. University_Type
   Jumlah unique values: 3
   Sample unique values: <StringArray>
['National University', 'Private University', 'Public University']
Length: 3, dtype: string
--------------------------------------------------
6. Stress_Level
   Jumlah unique values: 3
   Sample unique values: <StringArray>
['Medium', 'High', 'Low']
Length: 3, dtype: string
--------------------------------------------------

In [19]:
df.describe(include="all")

,Age,Gender,Study_Hours,Class_Attendance,Tuition,Exam_Frequency,Assignment_Load,Sleep_Hours,Caffeine_Intake_mg,Physical_Exercise,Social_Media_Use,Screen_Time,Family_Income_Level,Peer_Pressure,Family_Support,Anxiety_Level,University_Type,Stress_Score,Stress_Level
count,3000.000000,3000,3000.00000,3000.000000,3000,3000.000000,3000.000000,3000.000000,3000.000000,3000,3000.000000,3000.000000,3000,3000.000000,3000.000000,3000.000000,3000,3000.000000,3000
unique,NaN,2,NaN,NaN,2,NaN,NaN,NaN,NaN,2,NaN,NaN,3,NaN,NaN,NaN,3,NaN,3
top,NaN,Female,NaN,NaN,No,NaN,NaN,NaN,NaN,No,NaN,NaN,Medium,NaN,NaN,NaN,Public University,NaN,Medium
freq,NaN,1538,NaN,NaN,1545,NaN,NaN,NaN,NaN,1555,NaN,NaN,1342,NaN,NaN,NaN,1003,NaN,1431
mean,21.512333,NaN,4.48800,68.837333,NaN,5.021333,4.992667,6.514333,144.750000,NaN,3.500333,5.924333,NaN,4.983333,5.025667,5.002000,NaN,12.115667,NaN
std,1.712160,NaN,2.88189,17.429423,NaN,2.595212,2.588084,1.708440,101.939858,NaN,2.319869,3.175422,NaN,2.557323,2.563175,2.565058,NaN,6.423450,NaN
min,17.000000,NaN,0.00000,5.000000,NaN,0.000000,1.000000,0.000000,0.000000,NaN,0.000000,1.000000,NaN,1.000000,0.000000,1.000000,NaN,0.000000,NaN
25%,20.000000,NaN,2.00000,54.000000,NaN,3.000000,3.000000,5.000000,50.000000,NaN,2.000000,3.000000,NaN,3.000000,3.000000,3.000000,NaN,7.000000,NaN
50%,21.000000,NaN,4.00000,69.000000,NaN,5.000000,5.000000,7.000000,150.000000,NaN,3.000000,6.000000,NaN,5.000000,5.000000,5.000000,NaN,12.000000,NaN
75%,23.000000,NaN,7.00000,84.000000,NaN,7.000000,7.000000,8.000000,200.000000,NaN,5.000000,9.000000,NaN,7.000000,7.000000,7.000000,NaN,17.000000,NaN
max,24.000000,NaN,18.00000,99.000000,NaN,9.000000,9.000000,14.000000,650.000000,NaN,15.000000,11.000000,NaN,9.000000,9.000000,9.000000,NaN,33.000000,NaN

# **Conclusion**

Pada tahap Data Wrangling, dataset `university_student_stress_dataset.csv` telah melalui proses pengumpulan data, penilaian kualitas data, pembersihan data, dan validasi ulang.

Berdasarkan proses assessing, ditemukan beberapa masalah utama pada dataset, yaitu missing value, data duplikat, kesalahan tipe data pada kolom `Caffeine_Intake_mg`, nilai negatif pada beberapa kolom numerik, data kategorikal yang tidak konsisten, serta beberapa nilai invalid yang berada di luar rentang wajar.

Proses cleaning dilakukan dengan mengubah tipe data `Caffeine_Intake_mg` menjadi numerik, mengubah nilai negatif menjadi positif pada kolom numerik tertentu, memperbaiki nilai invalid menggunakan nilai yang lebih wajar atau median, menyeragamkan format data kategorikal, mengisi missing value numerik dengan median, mengisi missing value kategorikal dengan modus, serta menghapus data duplikat.

Setelah dilakukan validasi ulang, dataset sudah tidak memiliki missing value dan data duplikat. Selain itu, tipe data dan format nilai kategorikal juga sudah lebih konsisten. Dengan demikian, dataset hasil cleaning dapat digunakan untuk tahap berikutnya, yaitu Exploratory Data Analysis (EDA), untuk menganalisis faktor-faktor yang berkaitan dengan tingkat stres mahasiswa.

In [20]:
df.to_csv("../data/processed/university_student_stress_clean.csv", index=False)